server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.79.128:3306/ljx_cetc?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456

mybatis-plus:
  configuration:
    call-setters-on-nulls: true
  mapper-locations: classpath:/mybatis/mapper/*.xml